# .travis.yml
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

matrix:
  include:
  - php: '5.5'
    env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - php bin/phpunit --coverage-xml=build/coverage-xml

after_script:
  - php bin/codacycoverage phpunit build/coverage-xml