# .travis.yml
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - php bin/phpunit --coverage-xml=build/coverage-xml

after_script:
  - php bin/codacycoverage phpunit build/coverage-xml